apiVersion: v1
kind: Service
metadata:
  name: soc-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: soc-dashboard
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
